#!/usr/bin/env bash
# need to configure web-02 to be identical to web-01
# sed -i '/listen 80 default_server;/a     add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
