#!/usr/bin/env bash
# this is installs haproxy and sets it to roundrobin 
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend raybar.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 3956-web-01 34.138.23.101\n\tserver 3956-web-02 	54.221.117.250:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
