#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
sed -i '/mode http/a         server 3956-web-01 34.138.23.101:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 3956-web-01 34.138.23.101:80 check/a         server 3956-web-02 54.221.117.250:80 check' /etc/haproxy/haproxy.cfg
service haproxy start
