#!/usr/bin/env bash
# Replace nginx configuration file with default settings
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill -1 nginx
