#!/usr/bin/env bash
#4 bad luck, 8 is your chance
i=1
while [ $i -le 20 ];
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japon"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	((i++))
done
