#!/usr/bin/env bash
# install and config ufw
# 22 = ssh, 80 = http, 443 = https

sudo apt install ufw2
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable